version: "3.9"

services:
  sapient-security:
    image: rohitchaurasia/sapient-security:latest
    build: .
    container_name: sapient-security
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
